Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'graphQLOptions':
              position: 'before routing'
              component: 't3n\GraphQL\Http\HttpOptionsComponent'
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          graphQLRequestLogger:              
            default:
              class: Neos\Flow\Log\Backend\FileBackend
              options:
                logFileURL: '%FLOW_PATH_DATA%Logs/GraphQLRequests.log'
                createParentDirectories: true
                severityThreshold: '%LOG_INFO%'
                maximumLogFileSize: 10485760
                logFilesToKeep: 1
                logMessageOrigin: false

t3n:
  GraphQL:
    context: 't3n\GraphQL\Context'
    includeExceptionMessageInOutput: true
    endpoints: []
#      'some-endpoint':
#        'logRequests': true  # if enabled all requests are logged
#        'context:' 'Foo\Vendor\GraphQL\Context  # optional context that overrides the global context
#        'schemaEnvelope': 'Some\Fully\Qualified\Namespace'
